### PR TITLE
Feature/error handling

### PR DESCRIPTION
**Pull request by tomoyuki-tanaka**
- Updates exception handling for ad formats
- The SDK is updated from 5.1.4 to 5.2.0

### CODE REVIEW

**Comment by tomoyuki-tanaka** [comment]
マージ後materにも同期します

**Comment by mkaji-geniee** [comment]
LGTM

**Comment by tomoyuki-tanaka** [comment]
- corrected SDK version from 5.2.0 to 6.0.0
- upgraded adapter version to match SDK

**Comment by tomoyuki-tanaka** [comment]
- updates for Unity compatibility
- integrated into GNAdSamples
  - GNAdSampleBanner
  - GNAdSampleMultipleBanner
  - GNAdSampleNativeAd
  - GNAdSampleVideo

**Pull request merged**
